import type { Metadata } from 'next'
import { PropsWithChildren } from 'react'
import "./globals.css"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props:Readonly<PropsWithChildren<{}>>) {
  return (
    
      <html lang="en">
        <body className="m-0 bg-white">
            {props.children}
        </body>
      </html>
  )
}
